"""Fix references again

Revision ID: badd7e9a5689
Revises: ac6a3db53f67
Create Date: 2019-07-06 17:44:53.493533

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'badd7e9a5689'
down_revision = 'ac6a3db53f67'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('interval_id_location_fkey', 'interval', type_='foreignkey')
    op.create_foreign_key(None, 'interval', 'location', ['id_location'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'interval', type_='foreignkey')
    op.create_foreign_key('interval_id_location_fkey', 'interval', 'venue', ['id_location'], ['id'])
    # ### end Alembic commands ###
