"""Make address nullable

Revision ID: 4a0a428a06d3
Revises: 4fc5a650882b
Create Date: 2019-02-08 21:34:12.817031

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4a0a428a06d3'
down_revision = '4fc5a650882b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('venue', 'address',
               existing_type=sa.VARCHAR(length=256),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('venue', 'address',
               existing_type=sa.VARCHAR(length=256),
               nullable=False)
    # ### end Alembic commands ###
