"""Move venue fields to locations

Revision ID: 7b5c45939b93
Revises: f6476bb9f839
Create Date: 2019-04-04 23:21:45.203629

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7b5c45939b93'
down_revision = 'f6476bb9f839'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('location', sa.Column('email', sa.String(length=64), nullable=True))
    op.add_column('location', sa.Column('opening_hours', sa.Text(), nullable=True))
    op.add_column('location', sa.Column('phone', sa.String(length=32), nullable=True))
    op.drop_column('venue', 'phone')
    op.drop_column('venue', 'email')
    op.drop_column('venue', 'opening_hours')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('venue', sa.Column('opening_hours', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('venue', sa.Column('email', sa.VARCHAR(length=64), autoincrement=False, nullable=True))
    op.add_column('venue', sa.Column('phone', sa.VARCHAR(length=32), autoincrement=False, nullable=True))
    op.drop_column('location', 'phone')
    op.drop_column('location', 'opening_hours')
    op.drop_column('location', 'email')
    # ### end Alembic commands ###
