"""empty message

Revision ID: 7d366534b986
Revises: 4fc5a650882b
Create Date: 2019-02-09 16:43:32.069854

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '7d366534b986'
down_revision = '4fc5a650882b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('location',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('id_venue', sa.Integer(), nullable=False),
    sa.Column('address', sa.String(length=256), nullable=False),
    sa.Column('latitude', sa.Float(), nullable=False),
    sa.Column('longitude', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['id_venue'], ['venue.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('voucher',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('id_venue', sa.Integer(), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['id_venue'], ['venue.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('voucher_tag',
    sa.Column('id_voucher', sa.Integer(), nullable=False),
    sa.Column('tag', sa.Enum('BREAKFAST', 'MAIN_COURSE', 'SNACK', 'PASTRIES', 'ICE_CREAM', 'COFFEE', 'ALCOHOL', 'EVENT', 'TICKET', 'GUIDED_TOUR', 'WORKSHOP', 'SHOPPING', 'FREE_GIFT', 'COMBINATION', 'SEASONAL', name='tag'), nullable=False),
    sa.ForeignKeyConstraint(['id_voucher'], ['voucher.id'], ),
    sa.PrimaryKeyConstraint('id_voucher', 'tag')
    )
    op.create_table('voucher_type',
    sa.Column('id_voucher', sa.Integer(), nullable=False),
    sa.Column('type', sa.Enum('FOOD', 'DRINK', 'TICKET', name='type'), nullable=False),
    sa.ForeignKeyConstraint(['id_voucher'], ['voucher.id'], ),
    sa.PrimaryKeyConstraint('id_voucher', 'type')
    )
    op.drop_column('venue', 'latitude')
    op.drop_column('venue', 'address')
    op.drop_column('venue', 'longitude')
    op.drop_column('venue', 'venue_type')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('venue', sa.Column('venue_type', postgresql.ENUM('RESTAURANT', 'BAR', 'VENUE', name='venuetype'), autoincrement=False, nullable=True))
    op.add_column('venue', sa.Column('longitude', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False))
    op.add_column('venue', sa.Column('address', sa.VARCHAR(length=256), autoincrement=False, nullable=False))
    op.add_column('venue', sa.Column('latitude', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False))
    op.drop_table('voucher_type')
    op.drop_table('voucher_tag')
    op.drop_table('voucher')
    op.drop_table('location')
    # ### end Alembic commands ###
