"""Add inital intervals

Revision ID: d2ac0a3b4696
Revises: b120061631a2
Create Date: 2019-06-27 20:25:22.466670

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd2ac0a3b4696'
down_revision = 'b120061631a2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('interval',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('id_venue', sa.Integer(), nullable=False),
    sa.Column('start_hour', sa.Time(), nullable=False),
    sa.Column('end_hour', sa.Time(), nullable=False),
    sa.Column('start_day', sa.Integer(), nullable=False),
    sa.Column('end_day', sa.Integer(), nullable=False),
    sa.Column('start_month', sa.Integer(), nullable=False),
    sa.Column('end_month', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id_venue'], ['venue.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('interval')
    # ### end Alembic commands ###
